var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/why-etsy-listings-get-no-views/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__00qp5py._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_11p_3ft.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-f88ol._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k~tbvx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/0zjb_server_app_blog_why-etsy-listings-get-no-views_page_actions_0.m401c.js")
R.m(81370)
module.exports=R.m(81370).exports
